export { default as Navbar } from "./Navbar/Navbar"
export { default as Navbar2 } from "./Navbar/Navbar2"
export { default as Cart } from "../page/cart"
export { default as Hero } from "./Hero/Hero"
export { default as FarmarInfo } from "./farmarInfo/farmarInfo"
export { default as FarmerDashboard } from "./farmarInfo/FarmerDashboard"
export { default as Login } from "../page/Login"
export { default as customerDashboard } from "./CustomerProfile/CustomerDashboard"
export { default as CustomerSetting } from "./CustomerProfile/CustomerSetting"
export { default as CustomerProfile } from "../components/CustomerProfile/CustomerProfile"
export { default as Profile } from "./UserProfile"
export { default as OrderList } from "./farmarInfo/orderList"
export { default as Footer } from "./footer"
export { default as FarmerSetting } from "./farmarInfo/FarmerSetting"
export { default as VerifyEmail } from "../page/VerifyEmail"
export { default as ContactForm } from "../components/farmarInfo/ContactForm"
export { default as CustomerSideBar} from "./CustomerSideBar"
export { default as AdminDashboard} from "./admin/adminDashboard"
export { default as About } from "../page/About"
export { default as MarketPlace } from "./MarketPlace"
export { default as MyOrders } from "../page/MyOrders"
export { default as KhaltiSuccess } from "../page/KhaltiSuccess"
export { default as KhaltiFailure } from "../page/KhaltiFailure"



